export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const UPDATE_COUNTER = 'UPDATE_COUNTER';

export const  PRODUCT_ADD= "PRODUCT_ADD";
export const  PRODUCT_EDIT= "PRODUCT_EDIT";
export const  PRODUCT_REMOVE= "PRODUCT_REMOVE";
export const  PRODUCT_GET_ALL= "PRODUCT_GET_ALL";
export const  PRODUCT_GET= "PRODUCT_GET";
export const  START_FETCH_PRODUCT= "START_FETCH_PRODUCT";
export const  FINISH_FETCH_PRODUCT= "FINISH_FETCH_PRODUCT";
export const  ERROR_IN_FETCH_PRODUCT= "ERROR_IN_FETCH_PRODUCT";
